#!/bin/python3

import math
import os
import random
import re
import sys



def maxone(x):
    count= 0
    while(x!=0):
        x=(x & (x<<1))
        count = count + 1
    return count
x=int(input())
print(maxone(x))
#code by satyam#
